### ISSUE TITLE
Localstorage overflow

### ISSUE THREAD

**Issue by artttj** [artttj/plain-youtube-controls#2]
Need to implement cleaning of old videos timing data from the browser localstorage.

**Comment by prashcr** [comment]
I'll give it a try. What would we consider as "old"? Based on number of videos saved, or when it was saved? Or the localstorage limit?

**Comment by artttj** [comment]
@prashcr 
For now, we have a bunch of records in domain's localstorage where the key is ytc_VideoHash and the value is the last current time.

Maybe we will need to add a timestamp and check for the records that older than one month to clear them. Also, we could limit the number of the records too.

The main idea is that we shouldn't face the space limit.

**Comment by prashcr** [comment]
I don't think we'll need a limit on the number of records. I did some rough estimates.  

If a user watches  
1000 videos a day 
each record stores ~80 bytes  
(e.g. `{"lastTime":347,"timestamp":1475055924665}` is ~40 chars, each of which is 2 bytes)  

That's ~2.4 MB/month, so it's almost certain that just deleting videos older than a month will be enough.

**Comment by artttj** [comment]
@prashcr 

That's great! Thank you for research. I agree, it will be enough to remove records with the old videos.
